class GAController:
    def mutate_all(self) -> None: ...

    def crossover_all(self) -> None: ...

    def select_all(self) -> None: ...

    def handle_generation_errors(self) -> None: ...

    def run(self) -> None: ...

    @property
    def generation_cycle_time(self) -> int: ...

    @property
    def generation(self) -> int: ...

    @property
    def found_bugs(self) -> int: ...

    @property
    def found_bugs_types(self) -> set[Exception]: ...
